config/routes.rb
CmsEngine::Engine.routes.draw do
  resources :resources, only: %i[index new create edit update destroy]
  resources :templates, only: %i[index new create edit update destroy]
  resources :public_keys, only: %i[edit update]

  get 'api/:language/:template_path', to: 'api/resources#index', defaults: { format: :json }
  get 'api/:language/:template_path/:resource_path', to: 'api/resources#show', defaults: { format: :json }

  devise_for :users, class_name: "CmsEngine::User", module: 'devise', skip: [:passwords]


  # TODO - uncomment below, run `rake routes` -> generated routes should work - currently it doesn't work
  # devise_for :users, class_name: "CmsEngine::User", module: 'devise', skip: [:registrations, :passwords]
  # devise_scope :user do
  #   put    '/account',  to: 'devise/registrations#update'
  #   get    '/account',  to: 'devise/registrations#edit',   as: :edit_user_registration
  #   patch  '/account',  to: 'devise/registrations#update', as: :user_registration
  # end

end

app/models/cms_engine/application_record.rb
module CmsEngine
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/cms_engine/element.rb
module CmsEngine
  class Element
    include ActiveModel::Model

    # extending types array remember about adding new input in app/views/cms_engine/resources/inputs
    TYPES = %i[html string text int float]
    TYPES_STRING = TYPES.map(&:to_s)

    attr_accessor :key, :type, :content, :source

    validates :key, length: 2..255
    validates :type, inclusion: { in: TYPES_STRING }
    validate :keys_uniqueness


    def initialize(attributes = {})
      attributes.each do |name, value|
        send("#{name}=", value)
      end
    end

    def attributes
      { key: key, type: type, content: content }
    end

    private

    def keys_uniqueness
      return if source.elements.size == source.elements.map(&:key).uniq.size

      errors.add(:key, I18n.t('activerecord.errors.models.cms_engine.template.uniqueness'))
    end
  end
end

app/models/cms_engine/has_many_elements.rb
module CmsEngine
  module HasManyElements
    extend ActiveSupport::Concern

    included do
      validate :elements_validity
    end

    def elements
      memorized_elements = super
      raw_elements = memorized_elements.is_a?(String) ? JSON.parse(memorized_elements) : memorized_elements
      raw_elements.map { |element| Element.new(element.merge(source: self))}
    end

    private

    def elements_validity
      memorized_elements = elements
      return unless memorized_elements.select(&:invalid?).any?
      
      uniq_error_messages(memorized_elements).each do |key, messages|
        messages.each { |message| errors.add(key, message) }
      end
    end

    def uniq_error_messages(elements)
      acc = {}
      messages = elements.map { |el| el.errors.messages }
      messages.each do |message|
        message.keys.each { |key| acc[key] = (acc[key] || []) + (message[key] || []) }
      end
      acc.transform_values { |value| value.uniq }
    end
  end
end

app/models/cms_engine/public_key.rb
module CmsEngine
  class PublicKey < ApplicationRecord
    ALGORITHMS = %w[RS512]

    validates :algorithm, inclusion: { in: ALGORITHMS }
    validates :body, presence: true

  end
end

app/models/cms_engine/resource.rb
require 'paper_trail'

module CmsEngine
  class Resource < ApplicationRecord
    include CmsEngine::HasManyElements

    has_paper_trail versions: { class_name: 'CmsEngine::Version' }, on: [:update]

    AVAILABLE_LANGUAGES = I18n.available_locales

    validates :name, length: 2..255, uniqueness: { scope: :language }
    validates :path, length: 2..255, uniqueness: { scope: [:language, :cms_engine_template_id] }, format: { with: /\A[a-zA-Z0-9-_]*\z/ }

    belongs_to :template, class_name: 'CmsEngine::Template', foreign_key: 'cms_engine_template_id'

    def full_path
      "/#{language}/#{template.path}/#{path}".gsub("//", "/")
    end
  end
end

app/models/cms_engine/template.rb
module CmsEngine
  class Template < ApplicationRecord
    include CmsEngine::HasManyElements

    validates :name, length: 2..255, uniqueness: true
    validates :path, length: 2..255, uniqueness: true, format: { with: /\A[a-zA-Z0-9-_]*\z/ }

    has_many :resources, class_name: 'CmsEngine::Resource', foreign_key: 'cms_engine_template_id'
  end
end

app/models/cms_engine/user.rb
module CmsEngine
  class User < ApplicationRecord
    devise :database_authenticatable, :registerable,
           :rememberable, :validatable, :trackable
  end
end

app/models/cms_engine/version.rb
module CmsEngine
  class Version < PaperTrail::Version
    self.table_name = :cms_engine_versions
  end
end

app/controllers/cms_engine/api/resources_controller.rb
require_relative '../../../../lib/cms_engine/api_request_authorizer'

module CmsEngine
  module Api
    class ResourcesController < ActionController::API
      before_action :authorize_request

      def index
        render json: resources
      end


      def show
        resource = resources.find_by(path: params[:resource_path]) || raise(ActiveRecord::RecordNotFound)

        render json: resource
      end

      private

      def resources
        @resources ||= Resource.where(template: template, language: params[:language], published: true)
      end

      def template
        @template ||= Template.find_by(path: params[:template_path]) || raise(ActiveRecord::RecordNotFound)
      end

      def authorize_request
        return if ApiRequestAuthorizer.new(request).authorized?

        render json: { error: 'Not Authorized' }, status: 401
      end
    end
  end
end

app/controllers/cms_engine/application_controller.rb
module CmsEngine
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    # before_action :set_paper_trail_whodunnit # adds author to versions

  end
end

app/controllers/cms_engine/public_keys_controller.rb
require_dependency "cms_engine/application_controller"

module CmsEngine
  class PublicKeysController < ApplicationController
    before_action :set_public_key, only: %i[edit update]
    before_action :authenticate_user!

    # GET /public_keys/1/edit
    def edit
    end

    # PATCH/PUT /public_keys/1
    def update
      if @public_key.update(public_key_params)
        redirect_to edit_public_key_path(@public_key), notice: t('cms_engine.public_keys.update.success')
      else
        render :edit
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_public_key
        @public_key = PublicKey.first || PublicKey.create(body: 'public key body', algorithm: PublicKey::ALGORITHMS.first)
      end

      # Only allow a trusted parameter "white list" through.
      def public_key_params
        params.require(:public_key).permit(:body, :algorithm)
      end
  end
end

app/controllers/cms_engine/resources_controller.rb
require_dependency "cms_engine/application_controller"

module CmsEngine
  class ResourcesController < ApplicationController
    before_action :set_resource, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!

    # GET /resources
    def index
      @resources = Resource.all.order(:cms_engine_template_id, updated_at: :desc).includes(:template)
    end

    # GET /resources/1
    def show
    end

    # GET /resources/new
    def new
      @resource = Resource.new(elements: [Element.new])
    end

    # GET /resources/1/edit
    def edit
      if params[:version_timestamp].present?
        @resource = @resource.paper_trail.version_at(Time.zone.at(params[:version_timestamp].to_r))
      end
      @versions_datetimes = @resource.versions.order(created_at: :asc).pluck(:created_at).reverse
      @resources_with_other_languages = CmsEngine::Resource.where(name: @resource.name).where.not(language: @resource.language)
    end

    # POST /resources
    def create
      @resource = Resource.new(resource_params)
      @resource.elements = @resource.template.elements.map(&:attributes)

      if @resource.save
        redirect_to edit_resource_path(@resource), notice: 'Resource was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /resources/1
    def update
      if @resource.update(resource_params)
        redirect_to resources_url, notice: 'Resource was successfully updated.'
      else
        @versions_datetimes = @resource.versions.order(created_at: :asc).pluck(:created_at).reverse  
        @resources_with_other_languages = CmsEngine::Resource.where(name: @resource.name).where.not(language: @resource.language)
        render :edit
      end
    end

    # DELETE /resources/1
    def destroy
      @resource.destroy
      redirect_to resources_url, notice: 'Resource was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_resource
        @resource = Resource.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def resource_params
        params.require(:resource).permit(:cms_engine_template_id, :name, :path, :published, :language, elements: [:key, :type, :content])
      end
  end
end

app/controllers/cms_engine/templates_controller.rb
require_dependency "cms_engine/application_controller"

module CmsEngine
  class TemplatesController < ApplicationController
    before_action :set_template, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!

    # GET /templates
    def index
      @templates = Template.all
    end

    # GET /templates/1
    def show
    end

    # GET /templates/new
    def new
      @template = Template.new(elements: [Element.new])
    end

    # GET /templates/1/edit
    def edit
    end

    # POST /templates
    def create
      @template = Template.new(template_params)

      if @template.save
        redirect_to templates_url, notice: 'Template was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /templates/1
    def update
      if @template.update(template_params)
        redirect_to templates_url, notice: 'Template was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /templates/1
    def destroy
      @template.destroy
      redirect_to templates_url, notice: 'Template was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_template
        @template = Template.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def template_params
        params.require(:template).permit(:name, :path, elements: [:key, :type, :content])
      end
  end
end

app/helpers/cms_engine/application_helper.rb
module CmsEngine
  module ApplicationHelper
  end
end

app/helpers/cms_engine/resources_helper.rb
module CmsEngine
  module ResourcesHelper
    def render_input(input_type, form, key, options = {})
      # TODO fix html
      input_path = "cms_engine/resources/inputs/#{input_type}_input"
      fallback_path = 'cms_engine/resources/inputs/string_input'

      partial_path = partial_or_fallback_path(input_path, fallback_path)
      options = options.merge(id: SecureRandom.hex)
      render(partial_path, form: form, options: options, key: key)
    end

    private
    
    def partial_or_fallback_path(path, fallback_path)
      return path if lookup_context.template_exists?(path, [], true)

      fallback_path
    end
  end
end

app/helpers/cms_engine/templates_helper.rb
module CmsEngine
  module TemplatesHelper
  end
end

app/views/cms_engine/templates/_form.html.erb
<%= form_with(model: template, local: true) do |form| %>
  <% if template.errors.any? %>
    <div id="error_explanation" class='alert alert-danger'>
      <h2><%= pluralize(template.errors.count, "error") %> <%= t('cms_engine.templates.form.errors_message') %></h2>

      <ul>
      <% template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group'>
    <%= form.label t('cms_engine.templates.form.name') %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= form.label t('cms_engine.templates.form.path') %>
    <%= form.text_field :path, class: 'form-control'  %>
  </div>
  <br>
  <div class="card">
    <div id='elements-card' class="card-body">
      <h5 class="card-title"><%= t('cms_engine.templates.form.elements') %></h5>
      <% template.elements.each do |element| %>
        <div class="row element-row">
          <div class="col">
            <div class='form-group'>
              <%= form.label t('cms_engine.templates.form.key') %>
              <%= form.text_field 'elements[][key]', class: 'form-control', value: element.key  %>
            </div>
          </div>
      
          <div class="col">
            <div class='form-group'>
              <%= form.label t('cms_engine.templates.form.type') %>
              <%= form.select 'elements[][type]', options_for_select(CmsEngine::Element::TYPES, element.type), {}, class: 'form-control' %>
            </div>
          </div>
      
          <!--
          <div class="col">
            <div class='form-group'>
              <%= form.label t('cms_engine.templates.form.content') %>
              <%= form.text_field 'elements[][content]', class: 'form-control', value: element.content  %>
            </div> 
          </div>
          --->

          <div class="col left-center">
            <div type="button" class="btn btn-danger remove-element">
              <%= t('cms_engine.templates.form.remove') %>
            </div>
          </div>
        </div>
      <% end %>
      <button type="button" id='add-element' class="btn btn-secondary float-right">
        <%= t('cms_engine.templates.form.add') %>
      </button>
    </div>
  </div>
  <br>
  <div class='right-center'><%= form.submit t('cms_engine.templates.form.save'), class: 'btn btn-primary' %></div>
<% end %>

app/views/cms_engine/templates/edit.html.erb
<h1><%= t('cms_engine.templates.edit.title')%></h1>

<%= render 'form', template: @template %>

app/views/cms_engine/templates/index.html.erb
<% if notice.present? %>
  <p id="notice" class='alert alert-primary'><%= notice %></p>
<% end %>

<div class='container'>
  <div class="row">
    <div class="col">
      <h1><%= t('cms_engine.templates.index.title')%></h1>
    </div>
    <div class="col right-center">
      <%= link_to t('cms_engine.templates.index.create'), new_template_path, class: 'float-right align-middle btn btn-primary' %>
    </div>

  </div>
  <div class="row">
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= t('cms_engine.templates.index.name') %></th>
          <th><%= t('cms_engine.templates.index.path') %></th>
          <th><%= t('cms_engine.templates.index.last_edit') %></th>
          <th colspan="2"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @templates.each do |template| %>
          <tr>
            <td><%= template.name %></td>
            <td><%= template.path %></td>
            <td><%= template.updated_at %></td>
            <td><%= link_to t('cms_engine.templates.index.edit'), edit_template_path(template) %></td>
            <td><%= link_to t('cms_engine.templates.index.destroy'), template, method: :delete, data: { confirm: t('cms_engine.templates.index.destroy_confirmation') } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/cms_engine/templates/new.html.erb
<h1><%= t('cms_engine.templates.new.title')%></h1>

<%= render 'form', template: @template %>

app/views/cms_engine/templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @template.name %>
</p>

<p>
  <strong>Path:</strong>
  <%= @template.path %>
</p>

<p>
  <strong>Elements:</strong>
  <%= @template.elements %>
</p>

<%= link_to 'Edit', edit_template_path(@template) %> |
<%= link_to 'Back', templates_path %>